################################################################################
# Applications Kustomization
# Deploys application workloads
################################################################################
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/sample-gpu-app/overlays/dev
  prune: true
  wait: true
